# This is a template for service configuration, which have the metadata and settings for the services.

services:
  application1:
    name: Java Application
    language: java
    version: 18
    distribution:
    project_dir: Java
    project_file: pom.xml
  application2:
    name: Python Application
    language: python
    version: 3.12
    distribution:
    project_dir: Python
    project_file: requirements.txt
    
  sonar:
    sonar_organization: gitpranay5
    sonar_project_key: tm-application

  git:
    user-name: ex1
    user-email: guest@example.com

