# This is a template for service configuration, which have the metadata and settings for the services.

services:
  application1:
    name: Java Application
    language: java
    version: 17
    project_dir: Java
    project_file: pom.xml
  application2:
    name: Python Application
    language: python
    version: 3.12
    project_dir: Python
    project_file: requirements.txt