# This is a template for service configuration, which have the metadata and settings for the services.

service:
  - name: tm-application
    description: This is the configuration for the tm-application service.
    version: 1.0.0
    language: multi-language
    
project:
    project_dir: java-project
    project_file: pom.xml
    version: 18
    distribution: temurin

git:
    user-name: pranay
    user-email: ex@gmail.com