# This is a template for service configuration, which have the metadata and settings for the services.

service:
  - name: tm-application
    description: This is the configuration for the tm-application service.
    version: 1.0.0
    language: multi-language application
    
project:
    language: java
    project_dir: Java
    project_file: pom.xml
    version: 18
    distribution: temurin
    project_key: tm-application
    organization: gitpranay5

git:
    user-name: pranay
    user-email: ex@gmail.com

