# This is a template for service configuration, which have the metadata and settings for the services.

services:
  application1:
    name: Java Application
    language: java
    version: 18
    distribution:
    project_dir: Java
    project_file: pom.xml
  application2:
    name: Python Application
    language: python
    version: 3.12
    distribution:
    project_dir: Python
    project_file: requirements.txt

sonar:
  organization: gitpranay5
  project_key: tm-application

git:
  user-name: guest-1
  user-email: guest@example.com

