# This is a template for service configuration, which have the metadata and settings for the services.

services:
  application1:
    name: Java Application
    language: java
    version: 17
    project_dir: Java
    project_file: pom.xml

  application2:
    name: Python Application
    language: python
    version: 3.13
    project_dir: Python
    project_file: requirements.txt

  application3:
    name: Node.js Application
    language: node.js
    version: 24
    project_dir: Node
    project_file: package.json
