# This is my application ci workflow file

name: CI

permissions:
  contents: write
  pull-requests: write

on:
    workflow_dispatch:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
      types: [opened, synchronize, reopened]


jobs:
  parse-config:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.config.outputs.version }}
      project_dir: ${{ steps.config.outputs.project_dir }}
      project_file: ${{ steps.config.outputs.project_file }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Parse service config
        id: config
        run: |
          version=$(yq '.project.version' service-config.yml)
          project_dir=$(yq '.project.project_dir' service-config.yml)
          project_file=$(yq '.project.project_file' service-config.yml)
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "project_dir=$project_dir" >> "$GITHUB_OUTPUT"
          echo "project_file=$project_file" >> "$GITHUB_OUTPUT"

  build:
    uses: gitpranay5/tm-reusable/.github/workflows/java-build-bump.yml@feature
    with:
      version: ${{ needs.parse-config.outputs.version }}
      project_dir: ${{ needs.parse-config.outputs.project_dir }}
      project_file: ${{ needs.parse-config.outputs.project_file }}

