# This is my application ci workflow file

name: CI

permissions:
  contents: write
  pull-requests: write

on:
    workflow_dispatch:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
      types: [opened, synchronize, reopened]


jobs:
    build:
      uses: gitpranay5/tm-reusable/.github/workflows/java-build-bump.yml@main
      with:
        version: 17

