# This is my application ci workflow file

name: CI

on:
    workflow_dispatch:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
    build:
      uses: gitpranay5/tm-reusable/.github/workflows/java-build-bump.yml@feature
      with:
        version: 17