# This is my application ci workflow file

name: CI

permissions:
  contents: write
  pull-requests: write

on:
    workflow_dispatch:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
      types: [opened, synchronize, reopened]

jobs:
  build:
    uses: gitpranay5/tm-reusable/.github/workflows/multi-app-build.yml@feat
    with:
      service_config_file: service-config.yml
